Repository jupytercalpoly/jupyterlab-code-snippets, pull requests merged in 2020-08, with the labels that each got.

#55 Render code mirror to code snippet editor and restore state when the …
  src/CodeSnippetContentsService.ts
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditor.tsx
  src/CodeSnippetForm.ts
  src/CodeSnippetWidget.tsx
  src/CodeSnippetWidgetModel.ts
  src/PreviewSnippet.tsx
  src/index.ts
Labels: enhancement

#59 Render code mirror to code snippet editor and restore state when the …
  package.json
  src/CodeSnippetContentsService.ts
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditor.tsx
  src/CodeSnippetForm.ts
  src/CodeSnippetWidget.tsx
  src/CodeSnippetWidgetModel.ts
  src/index.ts
Labels: bug, enhancement

#64 Update README and package.json
  README.md
  package.json
Labels: documentation

#66 Fix binder issue
  binder/environment.yml
  binder/labextensions.txt
  binder/postBuild
  binder/requirements.txt
  binder/workspace.json
  snippets/import.json
  snippets/try statement.json
Labels: documentation, enhancement

#69 New snippet layout
  package.json
  snippets/import.json
  snippets/try statement.json
  src/CodeSnippetDisplay.tsx
  src/index.ts
  style/icon/jupyter_launcher.svg
  style/index.css
Labels: enhancement

#71 Validate input
  .eslintignore
  .eslintrc.js
  package.json
  src/CodeSnippetEditor.tsx
  src/CodeSnippetForm.ts
  src/index.ts
  style/index.css
  yarn.lock
Labels: enhancement

#73 Add lumino/widgets as dependency
  package.json
  src/CodeSnippetDisplay.tsx
  src/FilterSnippet.tsx
  src/FilterTools.tsx
  src/PreviewSnippet.tsx
  src/SearchBar.tsx
  style/index.css
  yarn.lock
Labels: dependencies

#78 Jahn96 snippet input
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditor.tsx
  src/CodeSnippetForm.tsx
  src/CodeSnippetInputDialog.ts
  src/CodeSnippetTags.tsx
  src/CodeSnippetWidget.tsx
  src/PreviewSnippet.tsx
  src/index.ts
  style/index.css
Labels: enhancement

#84 Snippet editor
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditor.tsx
  src/CodeSnippetEditorTags.tsx
  src/CodeSnippetInputDialog.ts
  src/CodeSnippetWidget.tsx
  src/index.ts
  style/index.css
Labels: bug, enhancement

#88 Test
  package.json
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditor.tsx
  src/CodeSnippetEditorTags.tsx
  src/CodeSnippetForm.tsx
  src/CodeSnippetInputDialog.ts
  src/CodeSnippetService.ts
  src/CodeSnippetWidget.tsx
  src/CodeSnippetWidgetModel.ts
  src/ConfirmMessage.tsx
  src/FilterTools.tsx
  src/MoreOptions.tsx
  src/PreviewSnippet.tsx
  src/UndoDelete.tsx
  src/index.ts
  style/icon/Jupyter_pencileditbutton_inactive.svg
  style/icon/check.svg
  style/icon/close_jupyter.svg
  style/icon/insertsnippet.svg
  style/icon/jupyter_launcher.svg
  style/icon/jupyter_pencileditbutton_hover.svg
  style/icon/jupyter_snippetarrow.svg
  style/icon/undoDelete.svg
  style/index.css
  yarn.lock
Labels: bug, dependencies

#96 Add comments and fix bug
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditorTags.tsx
  src/CodeSnippetForm.tsx
  src/CodeSnippetInputDialog.ts
  src/CodeSnippetWidget.tsx
  src/CodeSnippetWidgetModel.ts
  src/ConfirmMessage.tsx
  src/FilterTools.tsx
  src/MoreOptions.tsx
  src/PreviewSnippet.tsx
  src/index.ts
Labels: bug, documentation

#56 Repo progress
  PROGRESS.md
Labels: documentation

#102 Fix #98 #99
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditor.tsx
  src/CodeSnippetWidget.tsx
  src/ConfirmMessage.tsx
  src/FilterTools.tsx
Labels: bug

#105 Update code snippet extension to v1.0.2
  package.json
Labels: enhancement, version_update

#109 Change save short cut to accel shift s
  src/index.ts
Labels: enhancement

#110 JupyterLab Code Snippet Extension v1.0.3
  binder/workspace.json
  package.json
  snippets/.ipynb_checkpoints/untitled-checkpoint.txt
  snippets/carbon_emissions.json
  snippets/filter_income.json
  snippets/gdp_calculator.json
  snippets/generate_hundred.json
  snippets/import_cleaning.json
  snippets/life_exp_eur_asia.json
  snippets/lorenz_deriv.json
  snippets/matplotlib_import.json
  snippets/matrix_lstsqr.json
  snippets/most_frequent.json
  snippets/parallel_strings.json
  snippets/plotting_sine.json
  snippets/progress_bar.json
  snippets/sum_array.json
  snippets/time_calculation.json
Labels: version_update
