Repository jupytercalpoly/jupyterlab-code-snippets, pull requests merged in 2021-01, with the labels that each got.

#147 Update licensing and copyright
  LICENSE
  src/CodeSnippetContentsService.ts
  src/CodeSnippetDisplay.tsx
  src/CodeSnippetEditor.tsx
  src/CodeSnippetEditorTags.tsx
  src/CodeSnippetForm.tsx
  src/CodeSnippetInputDialog.ts
  src/CodeSnippetLanguages.ts
  src/CodeSnippetWidget.tsx
  src/CodeSnippetWidgetModel.ts
  src/ConfirmMessage.tsx
  src/FilterTools.tsx
  src/MoreOptions.tsx
  src/PreviewSnippet.tsx
  src/index.ts
  style/index.css
Labels: documentation

#153 Fix right-click to save cell(s) error.
  setup.py
  src/index.ts
Labels: enhancement

#152 Documentation
  .eslintignore
  Design/add_custom_snippet.png
  Design/add_snippet.png
  Design/codeSnippetEditor.png
  Design/options.png
  Design/search_filter.png
  babel.config.js
  coverage/CodeSnippetContentsService.ts.html
  coverage/CodeSnippetWidgetModel.ts.html
  coverage/base.css
  coverage/block-navigation.js
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/favicon.png
  coverage/index.html
  coverage/lcov-report/CodeSnippetContentsService.ts.html
  coverage/lcov-report/CodeSnippetWidgetModel.ts.html
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  coverage/prettify.css
  coverage/prettify.js
  coverage/sort-arrow-sprite.png
  coverage/sorter.js
  docs/contributor/codebase.rst
  docs/getting_started/changelog.rst
  docs/getting_started/installation.rst
  docs/getting_started/overview.rst
  docs/user/features.rst
  jest.config.js
  package.json
  src/CodeSnippetContentsService.ts
  src/ConfirmMessage.ts
  src/MoreOptions.ts
  src/PreviewSnippet.ts
  test/codeSnippetContentsService.test.ts
  test/codeSnippetWidgetModel.test.ts
  test/sample.test.ts
  testutils/jest-setup-files.js
  tsconfig.test.json
  yarn.lock
Labels: documentation

#150 Test our extension with Jest testing framework
  .eslintignore
  package.json
  test/codeSnippetEditor.test.tsx
  tsconfig.test.json
  yarn.lock
Labels: enhancement, test

#157 Jupyterlab binder update
  README.md
  binder/postBuild
  binder/requirements.txt
  binder/workspace.json
Labels: version_update

#162 Final update to 2.0
  README.md
  binder/postBuild
  docs/getting_started/changelog.rst
  docs/getting_started/installation.rst
  package.json
  src/CodeSnippetInputDialog.ts
Labels: UI/UX, documentation, version_update
